### PR TITLE
Include missing prerequisites from GUIDE.md

### PR DESCRIPTION
**Pull request by shawaj**
Added line for mcrypt and openssl which appear in GUIDE.md but not readme.txt

### CODE REVIEW

**Comment by shawaj** [comment]
would it be worth also including a lot more of the GUIDE.md text inside the readme.txt file under installation instructions / faq?

**Comment by sambohler** [comment]
Probably.  We're in the middle of updating a lot of documentation, and so we will be porting those changes over to readme.txt once we're done.

**Comment by shawaj** [comment]
sounds good, only reason I suggested it was because there seem to be people who, for whatever reason, don't seem to have realised the installation guide is on GitHub and have just ignored it. Just thought it might be good to put that info on WP as well.

**Comment by sambohler** [comment]
Thanks for the heads up!

**Comment by shawaj** [comment]
No problem at all. Thanks for merging the pull requests, glad they have
been useful.

**Pull request merged**
